تحديث ملف "اقرأني"، وجعله من اليمين لليسار
alifcommunity/compiler pull request #4
Opened 2021-03-13 21:01 UTC by ms2052001

تم تحديث أوامر الاستنساخ من الجيت والبناء

2021-03-13 22:50 UTC, hassandraga commented on README.md
> +git clone --depth=1 --branch=master https://github.com/alifcommunity/compiler.git alif-compiler
من فضلك غير إسم المجلد من alif-compiler إلى alif ربما سيكون أقصر وأفظل

2021-03-13 22:53 UTC, hassandraga requested changes
<div dir=rtl>من فضلك غير إسم المجلد من alif-compiler إلى alif ربما سيكون أقصر وأفظل</div>

2021-03-14 14:01 UTC, ms2052001 commented
تم تحسين أمر الاستنساخ من جيت

2021-03-14 17:07 UTC, merged

2021-03-14 17:07 UTC, hassandraga commented
شكرا لك