الاضافة الى المعيار رقم `051622`
alifcommunity/compiler pull request #54
Opened 2022-05-23 21:56 UTC by TheAwiteb

اضافة طريقة تعريف المتغيرات وطريقة كتابة الدوال، وتفاصيل حولهم مثل المتغير المتكيف والمتغير الغير متكيف، ومعطيات الدوال

2022-05-26 08:12 UTC, Shad7ows commented on alif_standards/المعايير/051622.md
> +المتغير الغير متكييف في ألف٤ هو متغير يمكنك تغير قيمته لكن لايمكنك تغير نوعه، وطريقة تعريف متغير غير متكيف هي بتحديد النوع الخاص به
المتغير الغير "متكيف" ... يمكنك "تغيير" قيمته

2022-05-26 08:21 UTC, Shad7ows commented on alif_standards/المعايير/051622.md
> +تٌعرَّف الدوال باستخدام الكلمة المفتاحية **`دالة`**، يتبعها نوع القيمة التي ترجعها الدالة، ولا يتم تحديد النوع المخرج من الدالة اذا كانت لاتخرج شي وسوف ترجع لك قيمة بنوع **`عادم`** (**أي لا قيمة لها*
اعتقد انه تم الإتفاق على عدم تحديد نوع مخرجات الدالة

2022-05-26 08:22 UTC, Shad7ows commented on alif_standards/المعايير/051622.md
> +ويتم وضع اقواس الدالة بعد اسمها وبعدها نقطتان رأسيتان
بدون نقطتان رأسيتنان فالدالة في ألف 4 تنتهي بالاقواس

2022-05-26 08:23 UTC, Shad7ows commented on alif_standards/المعايير/051622.md
> +يتم تحديد المعطيات التي تستقبلها الدالة داخل الاقواس الخاصة بها، ويجب عليك تحديد نوع المعطى الذي تستقبله الدالة، ويمكنك وضع قيمة افترضية ان أردت
لا يجب تحديد نوع المعطى ضمن الدالة

2022-05-26 08:25 UTC, Shad7ows commented on alif_standards/المعايير/051622.md
> +""" دالة لاترجع شي، اي انها سوف ترجع نوع "عادم" """
افضل الكلمة المفتاحية "عدم" بدل من "عادم" فهي انسب واصح لغوياً ومختصرة اكثر

2022-05-26 08:26 UTC, Shad7ows commented on alif_standards/المعايير/051622.md
> +دالة عدد ارجاع_عدد():
دالة ارجاع_عدد()
    ارجع 4
نهاية

2022-05-26 08:28 UTC, Shad7ows reviewed
تم تصحيح واقتراح بعض التعديلات أرجو المراجعة قبل الدمج

2022-05-27 10:05 UTC, TheAwiteb commented
قيل الدمج
- [ ] تدقيق لغوي
- [ ] الاتفاق على طريقة تعريف الدوال

2022-05-29 22:32 UTC, TheAwiteb commented
ازالة اسم المصمم لأن ألف4 صممت من قبل المجتمع، واضافة رابط الترخيص، وتعديل الرقم 4 من الرقم الهندي الى العربي

2022-05-30 07:37 UTC, me00001 commented
> وتعديل الرقم 4 من الرقم الهندي الى العربي

جميعها أرقام عربية مقبولة, أعرف ان المشهور انها هندية ولكن العرب استخدمها قبل 123 بقرون ولازلنا نستخدمها 
على اي حال تعديل الرقم مقبول بالنسبة لي لأن النوعين صحيح

2022-05-30 07:45 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +تٌعرَّف الدوال باستخدام الكلمة المفتاحية **`دالة`**، يتبعها نوع القيمة التي ترجعها الدالة، ولا يتم تحديد النوع المخرج من الدالة اذا كانت لاتخرج شي وسوف ترجع لك قيمة بنوع **`عادم`** (**أي لا قيمة لها*
![لقطة شاشة من 2022-05-30 10-44-25](https://user-images.githubusercontent.com/37930867/170942926-17556c9b-202e-4594-9841-09ce3270a132.png)

2022-05-30 07:46 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +""" دالة لاترجع شي، اي انها سوف ترجع نوع "عادم" """
ناقش هذا في المجتمع ثم نقرر بعد التصويت 🌹

2022-05-30 07:49 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +دالة عدد ارجاع_عدد():
![لقطة شاشة من 2022-05-30 10-48-20](https://user-images.githubusercontent.com/37930867/170943567-8edfc94c-024a-4b82-89c5-604a87de634a.png)
![لقطة شاشة من 2022-05-30 10-44-25](https://user-images.githubusercontent.com/37930867/170943606-901f203a-6d07-4b36-a0d0-471b1cbfa241.png)

تحتاج فقط مناقشة ارجاع/ارجع في المجتمع ثم انشاء تصويت 🌹

2022-05-30 08:28 UTC, me00001 requested changes
هذي التغييرات مطلوبة قبل الدمج

2022-05-30 08:28 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +بتم كتابة محتوى الدالة بعد النقطتان الرأسيتان **`:`** حتى **`نهاية دالة`** ويتم ارجاع قيمة من الدالة عبر الكلمة المفتاحية **`ارجع`**
```suggestion
بتم كتابة محتوى الدالة بعد القوسين **`()`** حتى **`نهاية دالة`** ويتم ارجاع قيمة من الدالة عبر الكلمة المفتاحية **`ارجع`**
```

2022-05-30 08:28 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +دالة عدد جمع_عددين(عدد الرقم_الاول، عدد الرقم_الثاني):
```suggestion
دالة عدد جمع_عددين(عدد الرقم_الاول، عدد الرقم_الثاني)
```

2022-05-30 08:28 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +دالة عدد ارجاع_عدد():
```suggestion
دالة عدد ارجاع_عدد()
```

2022-05-30 08:28 UTC, me00001 commented on alif_standards/المعايير/051622.md
> +دالة عدد جمع_عددين(عدد الرقم_الاول، عدد الرقم_الثاني = 10):
```suggestion
دالة عدد جمع_عددين(عدد الرقم_الاول، عدد الرقم_الثاني = 10)
```

2022-05-30 09:06 UTC, TheAwiteb commented
> هذي التغييرات مطلوبة قبل الدمج
في الاستفتاء تم اختيار النقطان
![image](https://user-images.githubusercontent.com/59842932/170957772-037991c0-842e-47ec-b651-df1aeea4cdd7.png)

2022-05-30 09:08 UTC, me00001 commented
> > هذي التغييرات مطلوبة قبل الدمج
> > في الاستفتاء تم اختيار النقطان
> > ![image](https://user-images.githubusercontent.com/59842932/170957772-037991c0-842e-47ec-b651-df1aeea4cdd7.png)

في المجموعة القديمة او الجديدة ؟

2022-06-26 16:31 UTC, merged